models/__init__.py
__author__ = 'damlin'
#coding=utf-8
from .user import *

models/user.py
__author__ = 'damlin'
#coding=utf-8
from exts import db
from flask.ext.principal import RoleNeed, UserNeed, Permission
from flaskext.mongoalchemy import BaseQuery
from werkzeug import cached_property
from datetime import datetime
from exts.permissions import admin
from exts.common import hash_str

now = datetime.now()


class HashField(db.StringField):
    def set_value(self, instance, value, from_db=False):
        print super(HashField, self).from_db
        if from_db:
            super(HashField, self).set_value(instance, value)
        else:
            super(HashField, self).set_value(instance, str(hash_str(value)))


class UserQuery(BaseQuery):
    def from_identity(self, identity):
        user = self.get(identity.id)
        if user:
            identity.provides.update(user.provides)
        identity.user = user
        return user

    def authenticate(self, name, password):
        user = self.filter(self.type.name == name).first()
        if user:
            authenticated = user.check_password(password)
            print authenticated
        else:
            authenticated = False
        return user, authenticated


class User(db.Document):
    query_class = UserQuery
    AUTH, ADMIN = 100, 200
    name = db.StringField()
    email = db.StringField()
    password = db.StringField()
    photo = db.StringField(default='')
    following_count = db.IntField(default=0)
    follower_count = db.IntField(default=0)
    post_count = db.IntField(default=0)
    active = db.BoolField(default=True)
    role = db.EnumField(db.IntField(), AUTH, ADMIN, default=AUTH)

    @db.computed_field(db.DateTimeField())
    def updated(self):
        return now

    @property
    def created_time(self):
        if self.has_id():
            return self.mongo_id.generation_time

    def check_password(self, password):
        if self.password is None:
            return False
        return self.password == hash_str(password)

    class Permissions(object):
        def __init__(self, obj):
            self.obj = obj

        @cached_property
        def edit(self):
            return Permission(UserNeed(self.obj.pk)) & admin

        @cached_property
        def delete(self):
            return Permission(UserNeed(self.obj.pk)) & admin

    @cached_property
    def pk(self):
        return str(self.mongo_id)

    @cached_property
    def permissions(self):
        return self.Permissions(self)

    @cached_property
    def provides(self):
        needs = [RoleNeed('auth'), UserNeed(self.pk)]
        if self.is_admin:
            needs.append(RoleNeed('admin'))
        return needs

    @property
    def is_admin(self):
        return self.role >= self.ADMIN

forms/__init__.py
__author__ = 'damlin'
#coding=utf-8
from .user import *

forms/user.py
__author__ = 'damlin'
#coding=utf-8
from flask import g
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import required, email, equal_to, ValidationError
from flask.ext.babel import gettext, lazy_gettext as _
from .validators import is_username
from models import User
from exts.common import hash_str


class LoginForm(Form):
    name = TextField(_('User Name:'), validators=[required(message=_('请输入用户名!'))])
    password = PasswordField(_('Password:'), validators=[required(message=_('请输入密码!'))])


class SignupForm(Form):
    name = TextField(_("User Name"), validators=[
        required(message=_("User Name required")), is_username])
    email = TextField(_("Email"), validators=[
        required(message=_("Email address required")),
        email(message=_("A valid email address is required"))
    ])
    password = PasswordField(_('Password:'), validators=[required(message=_('请输入密码!'))])

    def validate_name(self, field):
        user = User.query.filter_by(name=field.data and field.data.strip()).first()
        if user:
            raise ValidationError, gettext("This name is taken")

    def validate_email(self, field):
        user = User.query.filter_by(email=field.data and field.data.strip()).first()
        if user:
            raise ValidationError, gettext("This email is taken")


class ChangePasswordForm(Form):
    password_old = PasswordField(_('Old Password:'), validators=[required(message=_('请输入密码!'))])
    password = PasswordField(_('New Password:'), validators=[required(message=_('请输入新密码!'))])
    password_again = PasswordField(_("Password again"), validators=[equal_to("password", message=_("请和新密码保持一致!"))])

    def validate_password_old(self, field):
        if g.user is None or g.user.password != hash_str(field.data):
            raise ValidationError, gettext("当前密码输入错误!")

forms/validators.py
__author__ = 'damlin'
#coding=utf-8

from wtforms.validators import regexp
from flask.ext.babel import lazy_gettext as _

is_username = regexp(r'^\w+$', message=_("You can only use a-z,A-Z,0-9,_"))

exts/__init__.py
__author__ = 'damlin'
from .extensions import *

views/__init__.py
__author__ = 'damlin'
from .home import *
from .user import *
from .admin import *

views/admin.py
__author__ = 'damlin'
#coding=utf-8


from flask import Blueprint, render_template


admin = Blueprint('admin', __name__)


@admin.route('/admin')
def index():
    return render_template('admin/index.html')


@admin.route('/admin/new')
def new():
    return render_template('admin/new.html')

views/home.py
__author__ = 'damlin'
#coding=utf-8

from flask import Blueprint, render_template


home = Blueprint('home', __name__)


@home.route('/')
def index():
    return render_template('index.html')

views/user.py
__author__ = 'damlin'
#coding=utf-8

from flask import g, Blueprint, render_template, request, current_app, redirect, url_for
from flask.ext.principal import identity_changed, Identity, AnonymousIdentity
from models import User
from forms import LoginForm, SignupForm, ChangePasswordForm
from exts import photos
from exts.permissions import auth
from exts.common import hash_str

user = Blueprint('user', __name__)


@user.route('/<name>/')
def index(name):
    user = User.query.filter_by(name=name and name.strip()).first()
    if user:
        return render_template('user/index.html', user=user)
    return redirect(url_for('home.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == "POST" and form.validate():
        user, authenticated = User.query.authenticate(form.name.data, form.password.data)
        if user and authenticated:
            identity_changed.send(current_app._get_current_object(),
                                  identity=Identity(user.pk))
            return redirect('/user')
    return render_template('login.html', form=form)


@user.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm(request.form)
    if request.method == "POST" and form.validate():
        user = User()
        form.populate_obj(user)
        user.password = hash_str(form.password.data)
        user.save()
        return redirect('/user')
    return render_template('signup.html', form=form)


@user.route("/logout/")
def logout():
    identity_changed.send(current_app._get_current_object(),
                          identity=AnonymousIdentity())
    return redirect('/')


@user.route("/settings/", methods=['GET', 'POST'])
@auth.require(401)
def settings():
    form = ChangePasswordForm(request.form)
    return render_template('user/settings.html', form=form)


@user.route("/settings/password", methods=['POST'])
@auth.require(401)
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == "POST" and form.validate():
        user = User.query.filter_by(name=g.user.name).first()
        user.password = hash_str(form.password.data)
        user.save()
        return redirect(url_for('user.settings'))
    return redirect(url_for('user.settings'))


@user.route("/upload/", methods=['POST'])
@auth.require(401)
def upload():
    if request.method == 'POST' and 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        user = User.query.filter_by(name=g.user.name).first()
        user.photo = photos.url(filename)
        user.save()
    return redirect(url_for('user.settings'))

templates/common/common.html
{% macro render_user_sidebar(user) %}
    <div class="sidebar">
        <div class="widget">
            <div class="user-nav">
                <span class="user-image">
                {% if user.photo %}
                    <img src="{{  user.photo  }}">
                {% else %}
                    <img src="{{ url_for('static',filename='img/tumblr_static_avatar.png')}}">
                {% endif %}
                </span>
                <div class="user-info">
                    <h2 class="user-name">{{ user.name }}</h2>
                    <span class="user-count">{{ user.following_count }} follows / {{ user.post_count }} posts</span>
                </div>
                <div class="user-action">
                    <a class="btn btn-danger btn-lg btn-block" href="http://twitter.com/monstercritic" target="_blank">
                        Follow
                    </a>
                </div>
            </div>
        </div>

        <div class="widget">
            <div class="cell"><h4>修改密码</h4></div>
        </div>
    </div>
{% endmacro %}

templates/home.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ url_for('static',filename='css/base.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/responsive.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/page.css')}}" rel="stylesheet">

    <title>
        城觅 - 发现最近值得去做的事情

    </title>
</head>
<body>
<div id="wrapper">
<!-- 头部全部内容=================start -->
<div class="header_top"></div>
<header id="header">
    <div class="header_bg">
        <div class="header_back">
            <div class="header_logo fl">
                <a href="http://www.chengmi.com" alt="城觅"></a>
            </div>
            <div class="header_logoright fr"></div>
        </div>
    </div>
</header>
<!-- 头部全部内容=================end -->
<input type="hidden" name="_xsrf" value="52b580a422ae4cf5af2ea8fcccfec0cd"/>

<section id="section_filterall">
    <div class="section_filter f13">
        <div class="filter_classes_item fl">
            <div class="fl mr60 filter_classes_itemone">
                <label class="filter_classes_title fl fb">类别</label>
                <ul>

                    <li><a href="javascript:;" class="categoryselcss" data-action="all">全部</a></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="dining">美食</a></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="event">活动</a></li>
                    <li><span>戏剧</span></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="shopping">小店</a></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="food">食材</a></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="course">课程</a></li>
                    <li><a href="javascript:;" class="categoryselcss" data-action="other">其他</a></li>

                </ul>
            </div>
            <div class="fl filter_classes_itemone">
                <label class="filter_classes_title fl fb">时间</label>
                <ul>

                    <li><a href="javascript:;" class="timeselcss" data-action="all">全部</a></li>
                    <li><span>今天</span></li>
                    <li><a href="javascript:;" class="timeselcss" data-action="tomorrow">明天</a></li>
                    <li><a href="javascript:;" class="timeselcss" data-action="weekend">周末</a></li>
                    <li><a href="javascript:;" class="timeselcss" data-action="thisweek">最近一周</a></li>

                </ul>
            </div>
        </div>
    </div>
</section>
<section id="section_filterall_select">
    <div class="section_filter_select f13">
        <div class="section_filtersize900 mb">
            <select onchange="categorychange()" id="categorychangesel">
                <option value="all" >全部类别</option>
                <option value="dining" >美食</option>
                <option value="event" >活动</option>
                <option value="play" selected="selected">戏剧</option>
                <option value="shopping" >小店</option>
                <option value="food" >食材</option>
                <option value="course" >课程</option>
                <option value="other" >其他</option>
            </select>
        </div>
        <div class="section_filtersize900">
            <select onchange="timechange()" id="timechangesel">
                <option value="all" >全部时间</option>
                <option value="today" selected="selected">今天</option>
                <option value="tomorrow" >明天</option>
                <option value="weekend" >周末</option>
                <option value="thisweek" >最近一周</option>
            </select>
        </div>
    </div>
</section>
<section id="section">
    <div class="section_all">
        <ul class="section_ul">



            <!-- 块全部=================start -->
            <li class="iphone_li">
                <!-- 块内容标题=================start -->
                <div class="li_title">
                    <div class="li_title_tag fl" style="background-color:#74c493">
                        戏剧 </div>
                    <p class="fl f16 font_special">
                        <a href="/section/57" target="_blank" class="titleIndex">话剧「新青猿」</a>
                    </p>
                </div>
                <!-- 块内容标题=================end -->
                <!-- 块内容图片=================start -->
                <a href="/section/57" target="_blank" class="titleIndex">
                    <div class="iphone_250">





                        <img src="http://chengmi.b0.upaiyun.com/cm/fb5730fd-f8d0-4673-8f51-9f4037616479.jpg_cmindex250" class="section_all_img">
                        <!-- for pickey end -->
                    </div>
                </a>
                <!-- 块内容图片=================end -->
                <!-- 块内容个人信息=================start -->
                <div class="iphone_people">
                    <img src="http://chengmi.b0.upaiyun.com/avatar/a08131e2-1c76-48ad-a12a-62eeda89676c.jpg_headimg" class="content_portrait">
                    <p>
                        <span class="people_name">圆脸小杉杉</span>
<span class="people_time fr f12 pc3">
<span>6天前</span>

<span class="ml5 fb">想做</span>

</span>
                        </span>
                    </p>
                </div>
                <!-- 块内容个人信息=================end -->
                <!-- 块内容摘要=================start -->
                <div class="mb15">
                    <p class="li_title">极富创造性的导演将喜剧的核嵌进悲剧，12位奇葩演员历时2个月的排练变成手中锃锃发亮的利剑，给你从未有过的，<b>令你深深惊呆的观剧体验</b>。</p>
                </div>
                <!-- 块内容摘要=================end -->
            </li>
            <!-- 块全部=================end -->

            <!-- 块全部=================start -->
            <li class="iphone_li">
                <!-- 块内容标题=================start -->
                <div class="li_title">
                    <div class="li_title_tag fl" style="background-color:#74c493">
                        戏剧 </div>
                    <p class="fl f16 font_special">
                        <a href="/section/40" target="_blank" class="titleIndex">精工之鸟 舞剧「孔雀」</a>
                    </p>
                </div>
                <!-- 块内容标题=================end -->
                <!-- 块内容图片=================start -->
                <a href="/section/40" target="_blank" class="titleIndex">
                    <div class="iphone_250">





                        <img src="http://chengmi.b0.upaiyun.com/cm/2a22c629-2bfc-4cdd-8550-6b3099953a81.jpg_cmindex250" class="section_all_img">
                        <!-- for pickey end -->
                    </div>
                </a>
                <!-- 块内容图片=================end -->
                <!-- 块内容个人信息=================start -->
                <div class="iphone_people">
                    <img src="http://chengmi.b0.upaiyun.com/avatar/a08131e2-1c76-48ad-a12a-62eeda89676c.jpg_headimg" class="content_portrait">
                    <p>
                        <span class="people_name">圆脸小杉杉</span>
<span class="people_time fr f12 pc3">
<span>13-09-12</span>

<span class="ml5 fb">想做</span>

</span>
                        </span>
                    </p>
                </div>
                <!-- 块内容个人信息=================end -->
                <!-- 块内容摘要=================start -->
                <div class="mb15">
                    <p class="li_title">孔雀公主杨丽萍历时四十年的艺术沉淀，以一部惊艳开屏的舞剧《孔雀》完美收官。此后她将退居幕后，舞台生涯的<b>挂靴神作</b>，不容错过。<br /></p>
                </div>
                <!-- 块内容摘要=================end -->
            </li>
            <!-- 块全部=================end -->

            <!-- 块全部=================start -->
            <li class="iphone_li">
                <!-- 块内容标题=================start -->
                <div class="li_title">
                    <div class="li_title_tag fl" style="background-color:#74c493">
                        戏剧 </div>
                    <p class="fl f16 font_special">
                        <a href="/section/34" target="_blank" class="titleIndex">看剧大业「青戏节」</a>
                    </p>
                </div>
                <!-- 块内容标题=================end -->
                <!-- 块内容图片=================start -->
                <a href="/section/34" target="_blank" class="titleIndex">
                    <div class="iphone_250">





                        <img src="http://chengmi.b0.upaiyun.com/cm/1ee019fe-cb04-4420-bb6c-286cebd750c9.jpg_cmindex250" class="section_all_img">
                        <!-- for pickey end -->
                    </div>
                </a>
                <!-- 块内容图片=================end -->
                <!-- 块内容个人信息=================start -->
                <div class="iphone_people">
                    <img src="http://chengmi.b0.upaiyun.com/index/e9f19945-3486-4eb5-b820-845e4659c000.jpg_headimg" class="content_portrait">
                    <p>
                        <span class="people_name">小胖缘</span>
<span class="people_time fr f12 pc3">
<span>13-09-05</span>

<span class="ml5 fb">做过</span>

</span>
                        </span>
                    </p>
                </div>
                <!-- 块内容个人信息=================end -->
                <!-- 块内容摘要=================start -->
                <div class="mb15">
                    <p class="li_title">孟京辉老师在微博上以不怕传谣之势说：这是一个<b>特别牛逼的戏剧节。</b>你平常看不到想不到碰不到的牛逼戏剧齐集北京。～信不信由你，也不由你不信！</p>
                </div>
                <!-- 块内容摘要=================end -->
            </li>
            <!-- 块全部=================end -->


        </ul>
        <div class="bottom_loading" style="display: none">
<span>
<img src="/static/images/loading.gif?v=b016b"
     class="load_more_img">请稍等，努力加载数据中
</span>
            <input type="hidden" id="hiddenpage" value="1" />
        </div>
    </div>
</section>
<input type="hidden" id="hiddentime" value="today" />
<input type="hidden" id="hiddencategory" value="play" />

<footer id="footer">
    <div class="footer_bg">
        <div class="footer_wrapper">
            <div class="fl footer_l">
                <p class="fl">
                    <img src="{{ url_for('static',filename='img/weibo.png')}}" class="footer_img">
                    新浪微博
                    <a href="http://e.weibo.com/chengmicom" class="footlink" target="_blank">@Story</a>
                </p>
                <p class="fl">
                    <img src="{{ url_for('static',filename='img/weixin.png')}}" class="footer_img">
                    微信公众账号 Story
                </p>
            </div>
            <div class="footer_r">
                <p>
                    <a href="http://www.chengmi.com" class="footlink">Story</a>
                    © 2013 京ICP备11041926号-5
                </p>
            </div>
        </div>
    </div>
</footer>
</div>
<script src="{{ url_for('static',filename='js/jquery-1.10.2.min.js')}}"></script>
<script src="{{ url_for('static',filename='js/tools.js')}}"></script>
<script src="{{ url_for('static',filename='js/ga.js')}}"></script>

<script src="{{ url_for('static',filename='js/index.js')}}"></script>
<script src="{{ url_for('static',filename='js/loadmore.js')}}"></script>

</body>
</html>

templates/index.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-content" id="page-content">
    <div class="container">
        <div class="ui-categories">
            <div class="ui-categories-l">
                <div class="ui-categories-icon-1">筛选：</div>
            </div>
            <div class="ui-categories-r">
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
                <a href="/tejia">全部</a>
            </div>
        </div>
    </div> <!-- /container -->
    </div> <!-- /page-content -->
{% endblock %}

templates/layouts/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{#    <!-- Le styles -->#}
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.css')}}">#}
{##}
{#    <!--[if lte IE 6]>#}
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap-ie6.css')}}">#}
{#    <![endif]-->#}
{#    <!--[if lte IE 7]>#}
{#    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/ie.css')}}">#}
{#    <![endif]-->#}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/story-responsive.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css')}}">

    <title>story</title>
</head>
<body>
<!-- 头部全部内容=================start -->
<header class="page-head" id="page-header">
    <div class="header_top"></div>
    <div class="container">
        <div class="header_back">
            <h1 class="site-title">
                <a href="/">Story Demo</a>
            </h1>
            <div class="social-links">
                {% if g.user %}
                <a href="/">创建Story</a>
                <a href="{{ url_for('user.index',name=g.user.name) }}">个人主页</a>
                <a href="{{ url_for('user.settings') }}">设置</a>
                <a href="{{ url_for('user.logout',next=request.path) }}">退出</a>
                {% else %}
                <a href="{{ url_for('user.login',next=request.path) }}">登录</a>
                <a href="{{ url_for('user.signup',next=request.path) }}">注册</a>
                {% endif %}
            </div>
        </div>
    </div> <!-- /container -->
</header> <!-- /page-head -->


{% block content %}
{% endblock %}


<div id="footer">
    <div class="footer_bg">
        <div class=" container footer_wrapper">
            <div class="footer_l">
                <p class="fl">
                    <img src="{{ url_for('static',filename='img/weibo.png')}}" class="footer_img">
                    新浪微博
                    <a href="http://e.weibo.com/chengmicom" class="footlink" target="_blank">@Story</a>
                </p>
                <p class="fl">
                    <img src="{{ url_for('static',filename='img/weixin.png')}}" class="footer_img">
                    微信公众账号 Story
                </p>
            </div>
            <div class="footer_r">
                <p>
                    <a href="http://www.chengmi.com" class="footlink">Story</a>
                    © 2013 京ICP备11041926号-5
                </p>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/login.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-content" id="page-content">
        <div class="container">
            <div class="widget">
                <form id="login_form" action="." method="post">
                    {{ form.csrf_token }}
                    <div class="form-control">
                        <label class="control-label" for="name">用户名:</label>
                        <div class="controls">
                            <input type="text" class="form-input" id="name" name="name" placeholder="User Name">
                        </div>
                    </div>
                    <div class="form-control">
                        <label class="control-label" for="password">密码:</label>
                        <div class="controls">
                            <input type="password" class="form-input" id="password" name="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-control">
                        <div class="controls">
                            <button type="submit" class="btn btn-lg btn-primary btn-block">登录</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-content" id="page-content">
        <div class="container">
            <div class="widget">
                <form id="login_form" action="." method="post">
                    {{ form.csrf_token }}
                    <div class="form-control">
                        <label class="control-label" for="email">电子邮件:</label>
                        <div class="controls">
                            <input type="text" class="form-input" id="email" name="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-control">
                        <label class="control-label" for="name">用户名:</label>
                        <div class="controls">
                            <input type="text" class="form-input" id="name" name="name" placeholder="User Name">
                        </div>
                    </div>
                    <div class="form-control">
                        <label class="control-label" for="password">密码:</label>
                        <div class="controls">
                            <input type="password" class="form-input" id="password" name="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-control">
                        <div class="controls">
                            <button type="submit" class="btn btn-lg btn-primary btn-block">注册</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/index.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-content" id="page-content">
        <div class="container">

            <div class="posts">
                <div class="widget"></div>
            </div>

            {% from "common/common.html" import render_user_sidebar %}
            {{ render_user_sidebar(user) }}

        </div>
    </div>
{% endblock %}

templates/user/settings.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-content" id="page-content">
        <div class="container">
            <div class="posts">
                <div class="widget">
                    <div class="cell">头像上传</div>
                    <form id="upload_form" action="{{ url_for('user.upload') }}" enctype="multipart/form-data" method="post">
                        {{ form.csrf_token }}

                        <div class="form-control">
                            <label class="control-label">当前头像:</label>
                            <div class="controls">
                                {% if g.user.photo %}
                                    <img src="{{  g.user.photo  }}">
                                {% else %}
                                    <img src="{{ url_for('static',filename='img/tumblr_static_avatar.png')}}">
                                {% endif %}
                            </div>
                        </div>

                        <input type=file name=photo>

                        <div class="form-control">
                            <div class="controls">
                                <button type="submit" class="btn btn-lg btn-primary btn-block">开始上传</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="widget">
                    <div class="cell">更改密码</div>
                    <form id="login_form" action="{{ url_for('user.change_password') }}" method="post">
                        {{ form.csrf_token }}
                        <div class="form-control">
                            <label class="control-label" for="password_old">当前密码:</label>
                            <div class="controls">
                                <input type="password" class="form-input" id="password_old" name="password_old">
                            </div>
                        </div>

                        <div class="form-control">
                            <label class="control-label" for="password">新密码:</label>
                            <div class="controls">
                                <input type="password" class="form-input" id="password" name="password">
                            </div>
                        </div>

                        <div class="form-control">
                            <label class="control-label" for="password_again">再次输入新密码:</label>
                            <div class="controls">
                                <input type="password" class="form-input" id="password_again" name="password_again" >
                            </div>
                        </div>

                        <div class="form-control">
                            <div class="controls">
                                <button type="submit" class="btn btn-lg btn-primary btn-block">更改密码</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            {% from "common/common.html" import render_user_sidebar %}
            {{ render_user_sidebar(g.user) }}

        </div>
    </div>
{% endblock %}